### PR TITLE
Modifying the Github actions file

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Hey @schristoff I have modified the action file and here the **Golang version** is used from **env** avoid installing it  **everytime** . Just a small question that should I seperate the file one on push and one on Pull Request?

### CODE REVIEW

**Comment by schristoff** [comment]
Hey,
Yeah I think it makes sense to have one that runs on pull requests and one that runs on merge into main (push into main)
The push into main one would have the `publish` built into it
```
    - name: Publish
      if: success() && github.event_name != 'PullRequest'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: mage Publish
```

**Comment by Bharadwajshivam28** [comment]
> Hey, Yeah I think it makes sense to have one that runs on pull requests and one that runs on merge into main (push into main) The push into main one would have the `publish` built into it
> 
> ```
>     - name: Publish
>       if: success() && github.event_name != 'PullRequest'
>       env:
>         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
>       run: mage Publish
> ```

Okay I will make the changes requried

**Comment by Bharadwajshivam28** [comment]
Hey @schristoff I have seperated 2 files one for push and another on pull request also changed the file names .

**Comment by kichristensen** [comment]
This was implemented in https://github.com/getporter/skeletor/pull/51

**Pull request closed without merging**
